# Generated by Django 4.2.4 on 2023-08-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_rename_comment_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=128, verbose_name='Ismi')),
                ('phone', models.CharField(max_length=128, verbose_name='telefon')),
                ('xabar', models.TextField(verbose_name='xabar')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_trash', models.BooleanField(default=False)),
                ('is_contacted', models.BooleanField(default=False)),
            ],
        ),
    ]
